import streamlit as st
import datetime
import os
import sys
import time
import re
from dotenv import load_dotenv

from agent.agentic_workflow import GraphBuilder

load_dotenv()

st.set_page_config(
    page_title="🌍 Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

def invoke_with_retry(react_app, messages: dict, max_retries: int = 4) -> dict:
    """Invoke the graph with automatic retry on rate-limit (429) errors."""
    last_error = None
    for attempt in range(1, max_retries + 1):
        try:
            return react_app.invoke(messages)
        except Exception as e:
            err_str = str(e)
            is_rate_limit = (
                "429" in err_str or
                "rate_limit_exceeded" in err_str or
                "Rate limit" in err_str or
                "Request too large" in err_str or
                "OTPM" in err_str or
                "TPM" in err_str or
                "output tokens per minute" in err_str or
                "tokens per minute" in err_str
            )
            if is_rate_limit:
                if "output tokens per minute" in err_str or "OTPM" in err_str or "Request too large" in err_str:
                    wait_seconds = 62.0
                else:
                    wait_seconds = 15.0 * attempt
                    match = re.search(r"try again in (\d+\.?\d*)s", err_str)
                    if match:
                        wait_seconds = float(match.group(1)) + 3
                print(f"[Rate limit] Attempt {attempt}/{max_retries}. Waiting {wait_seconds:.0f}s before retry...")
                time.sleep(wait_seconds)
                last_error = e
            else:
                raise e
    raise last_error

st.title("🌍 Travel Planner Agentic Application")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat history
st.header("How can I help you in planning a trip? Let me know where do you want to visit.")

# Chat input box at bottom
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="e.g. Plan a trip to Goa for 5 days")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        # Show thinking spinner while backend processes
        with st.spinner("Bot is thinking..."):
            
            # Initialize GraphBuilder directly inside Streamlit (No API needed!)
            graph = GraphBuilder(model_provider="groq")
            react_app = graph()
            
            messages_payload = {"messages": [user_input]}
            
            # Call agent logic directly
            output = invoke_with_retry(react_app, messages_payload, max_retries=3)

            # If result is dict with messages:
            if isinstance(output, dict) and "messages" in output:
                answer = output["messages"][-1].content  # Last AI response
            else:
                answer = str(output)

        markdown_content = f"""# 🌍 AI Travel Plan

        # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
        # **Created by:** Atriyo's Travel Agent

        ---

        {answer}

        ---

        *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
        """
        st.markdown(markdown_content)

    except Exception as e:
        st.error(f"Failed to process your request. Error: {str(e)}")